name: Pull Request Check Release

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    if: github.head_ref == 'develop'  # Zorg ervoor dat de bronbranch 'develop' is
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Start virtual display
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x16 &
          export DISPLAY=:99

      - name: Run Tests
        run: ./gradlew test -Djava.awt.headless=true
        env:
          DISPLAY: :99

  create-jar:
    runs-on: ubuntu-latest
    needs: unit-test
    if: github.head_ref == 'develop'  # Alleen uitvoeren als de bronbranch 'develop' is
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'oracle'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Start virtual display
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x16 &
        env:
          DISPLAY: :99

      - name: Build Jar
        run: ./gradlew build -Djava.awt.headless=true
        env:
          DISPLAY: :99

      - name: Move Jar to staging directory
        run: mkdir staging && cp build/libs/*.jar staging

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: staging

  create_release:
    runs-on: ubuntu-latest
    needs: create-jar
    if: github.head_ref == 'develop'  # Alleen uitvoeren als de bronbranch 'develop' is
    permissions:
      contents: write
      packages: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v4
        with:
          tag_name: v${{ secrets.VERSION }}
          release_name: Release v${{ secrets.VERSION }}
          body: |
            Release v${{ secrets.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./staging/*.jar
          asset_name: MyProject-${{ secrets.VERSION }}.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  write-comment-on-unit-test-failure:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: unit-test
    if: failure() && github.head_ref == 'develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write comment on PR failure
        uses: mshick/add-pr-comment@v2
        with:
          message: 'There were errors during the unit test process.'

  write-comment-on-create-jar-failure:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: create-jar
    if: failure() && github.head_ref == 'develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write comment on PR failure
        uses: mshick/add-pr-comment@v2
        with:
          message: 'There were errors during the creating jar process.'
